#!/bin/bash

show_help() {
    echo "Usage: $0 <command> [options]"
    echo "Commands:"
    echo "  load [0:Immediate, 1:Per-task, 2:Global] [file1,file2,...] [Timeout seconds]   Load BPF kprobes for listed files"
    echo "  unload                   Unload all loaded BPF kprobes"
    exit 1
}

if [ $# -lt 1 ]; then
    show_help
fi

COMMAND=$1

if [ "$COMMAND" = "load" ]; then
    if [ -z "$2" ] || [ -z "$3" ]; then
        echo "Missing argument: [0:Immediate, 1:Per-task, 2:Global] [file1,file2,...] [Timeout seconds]"
        exit 1
    fi
    MODE=$2
    if [ "$MODE" -ne 0 ] && [ "$MODE" -ne 1 ] && [ "$MODE" -ne 2 ]; then
        echo "Invalid mode: $MODE"
        exit 1
    fi
    FILES=$3
    if [ -z "$FILES" ]; then
        echo "Missing argument: [file1,file2,...]"
        exit 1
    fi
    LOADER="./bpf_kprobe/kprobe_loader"
    if [ ! -f "$LOADER" ]; then
        echo "kprobe_loader not found at $LOADER"
        exit 1
    fi

    echo "[Step 1] Loading kfuncs module..."
    sudo insmod ./kernel_module/kfuncs/xk-kfuncs.ko kMode=$MODE
    
    echo "[Step 2] Successfully loading BPF Kprobes:"
    sudo "$LOADER" --files "$FILES" --pin
    STATUS=$?
    if [ $STATUS -ne 0 ]; then
        echo "Failed to load kprobes. You can try xkernel-tool unload and load again."
        exit $STATUS
    fi

    echo "[Step 3] Loading consistency module for transition..."
    timeout=$4

    if [ -z "$timeout" ]; then
        sudo insmod ./kernel_module/consistency/xk-consistency.ko
    else
        sudo insmod ./kernel_module/consistency/xk-consistency.ko kTimeout=$timeout
    fi

    echo "Check dmesg to see if the transition is successful."

elif [ "$COMMAND" = "unload" ]; then
    echo "[Step 1] Unloading consistency module for transition..."
    sudo rmmod xk-consistency

    echo "[Step 2] Unloading BPF Kprobes..."
    sudo rm -rf /sys/fs/bpf/xkernel

    # Give bpf tools time to detach the kprobes.
    sleep 2
    echo "[Step 3] Unloading kfuncs module..."
    sudo rmmod xk-kfuncs
    
    echo "Check dmesg to see if the transition is successful."

    exit 0
else
    show_help
fi

