// SPDX-License-Identifier: GPL-2.0
//
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!  AUTO-GENERATED by codegen.py — DO NOT EDIT THIS FILE  !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
//
// SIE indirection stub for ConstID 7
// Regenerate with: ./xkernel-tool build
#ifndef __XTUNE_STUB_7_H__
#define __XTUNE_STUB_7_H__

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>

#include "xkernel.bpf.h"
#include "cs_artifact.bpf.h"

// SIE helper 0: simple -> %eax
static __always_inline void __sie_7_0(struct pt_regs *regs, u64 val) {
    u64 new_val = val;
    sie_write_kernel(&regs->ax, sizeof(regs->ax), &new_val);
}

#define X_TUNE_0(func_name, location_str) \
    static int __xk_policy_7_0(struct x_ctx *x_ctx, struct pt_regs *ctx); \
    SEC("kprobe/" #func_name location_str) \
    int BPF_KPROBE(__xk_7_0) { \
        struct x_ctx __x_ctx = { .regs = ctx, .set_fn = &__sie_7_0 }; \
        return __xk_policy_7_0(&__x_ctx, ctx); \
    } \
    static int __xk_policy_7_0(struct x_ctx *x_ctx, struct pt_regs *ctx)

#endif // __XTUNE_STUB_7_H__
