kernel_dir = "~/linux-6.8.0"

name = "MAX_SOFTIRQ_RESTART"
description = "kernel/softirq.c MAX_SOFTIRQ_RESTART"

[source]
file = "kernel/softirq.c"
original = "#define MAX_SOFTIRQ_RESTART 10"
modified = ["#define MAX_SOFTIRQ_RESTART 5", "#define MAX_SOFTIRQ_RESTART 3"]
values = [10, 5, 3]
