# In[1]:

#!/usr/bin/env python3

import sys
import pandas as pd
import matplotlib.pyplot as plt

latex_macros = []

# In[2]:


analysis_time_csv_file = 'kernel-results/overhead.csv'

df = pd.read_csv(analysis_time_csv_file)

if df.shape[1] < 3:
    print("CSV must have at least 3 columns")
    sys.exit(1)

analysis_time_minutes = df.iloc[:, 1]

analysis_time_minutes_mean = analysis_time_minutes.mean()
analysis_time_minutes_stddev = analysis_time_minutes.std()
analysis_time_minutes_max = analysis_time_minutes.max()

analysis_time_minutes_mean_str = "{:.0f}".format(analysis_time_minutes_mean)
analysis_time_minutes_stddev_str = "{:.0f}".format(analysis_time_minutes_stddev)
analysis_time_minutes_max_str = "{:.0f}".format(analysis_time_minutes_max)

latex_macros.append(f"\\newcommand{{\\wentaoNumbersSsAnalysisTimeMean}}{{{analysis_time_minutes_mean_str}\\xspace}}")
latex_macros.append(f"\\newcommand{{\\wentaoNumbersSsAnalysisTimeStddev}}{{{analysis_time_minutes_stddev_str}\\xspace}}")
latex_macros.append(f"\\newcommand{{\\wentaoNumbersSsAnalysisTimeMax}}{{{analysis_time_minutes_max_str}\\xspace}}")

# In[3]:

with open('paper-assets/numbers_auto.tex', 'w') as f:
    f.write("""% Autogenerated. Do not modify by hand.
% https://github.com/zhongjiechen/Xkernel/tree/dataflow/paper-assets

""")
    f.write("\n".join(latex_macros))
    f.write("\n")
