# In[1]:

#!/usr/bin/env python3

import sys
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
import re

latex_macros = []

skip_macro_list = [
    # Huge IR diff
    'MLD_MAX_QUEUE',
    'MAX_MADVISE_GUARD_RETRIES',
    'MAX_VMAP_RETRIES',
    'TCP_DELACK_MAX',

    # Not in all-cases.txt
    'Try_KLP_bad_case',
]

# In[2]:


analysis_time_csv_file = 'kernel-results/overhead.csv'

df = pd.read_csv(analysis_time_csv_file)

if df.shape[1] < 3:
    print("CSV must have at least 3 columns")
    sys.exit(1)

# Remove rows where the first column matches any skip macro

# print(f"Original {len(df)} cases")

pattern = re.compile(r'^kernel-results/([^/]+)/')
def is_skip_macro(row):
    m = pattern.match(str(row.iloc[0]))
    if m:
        macro_name = m.group(1)
        return macro_name in skip_macro_list
    return False

df = df[~df.apply(is_skip_macro, axis=1)].reset_index(drop=True)

# print(f"Original {len(df)} cases")

analysis_time_minutes = df.iloc[:, 1]

analysis_time_minutes_mean = analysis_time_minutes.mean()
analysis_time_minutes_stddev = analysis_time_minutes.std()
analysis_time_minutes_max = analysis_time_minutes.max()

idx_analysis_time_minutes_max = analysis_time_minutes.idxmax()
max_analysis_time_file_name = df.iloc[idx_analysis_time_minutes_max, 0].strip()
max_analysis_time_macro_name = max_analysis_time_file_name.split('/')[1].strip()
max_analysis_time_macro_name_latex = str(max_analysis_time_macro_name).replace('_', '\\_')
max_analysis_time_macro_name_latex = f"\\texttt{{{max_analysis_time_macro_name_latex}}}"
with open(Path(max_analysis_time_file_name).parent / 'ss-size2.txt', 'r') as f:
    content = f.read()
    total_instructions = re.search(r'Total: (\d+) instructions', content).group(1)
    total_instructions = int(total_instructions)
    max_analysis_time_instructions = total_instructions
    max_analysis_time_instructions_str = "{:,.0f}".format(max_analysis_time_instructions)

analysis_time_minutes_mean_str = "{:.0f}".format(analysis_time_minutes_mean)
analysis_time_minutes_stddev_str = "{:.0f}".format(analysis_time_minutes_stddev)
analysis_time_minutes_max_str = "{:.0f}".format(analysis_time_minutes_max)

latex_macros.append(f"\\newcommand{{\\wentaoNumbersSsAnalysisTimeMean}}{{{analysis_time_minutes_mean_str}\\xspace}}")
latex_macros.append(f"\\newcommand{{\\wentaoNumbersSsAnalysisTimeStddev}}{{{analysis_time_minutes_stddev_str}\\xspace}}")
latex_macros.append(f"\\newcommand{{\\wentaoNumbersSsAnalysisTimeMax}}{{{analysis_time_minutes_max_str}\\xspace}}")

latex_macros.append(f"\\newcommand{{\\wentaoNumbersSsAnalysisTimeMaxMacro}}{{{max_analysis_time_macro_name_latex}\\xspace}}")
latex_macros.append(f"\\newcommand{{\\wentaoNumbersSsAnalysisTimeMaxInstructions}}{{{max_analysis_time_instructions_str}\\xspace}}")

df = pd.read_csv('kernel-results/per-perf-const-size.txt')
ss_size_median = df.iloc[:, 0].median()
ss_size_median_str = "{:,.0f}".format(ss_size_median)

latex_macros.append(f"\\newcommand{{\\wentaoNumbersSsSizeMedian}}{{{ss_size_median_str}\\xspace}}")

# In[3]:

with open('paper-assets/numbers_auto.tex', 'w') as f:
    f.write("""% Autogenerated. Do not modify by hand.
% https://github.com/zhongjiechen/Xkernel/tree/dataflow/paper-assets

""")
    f.write("\n".join(latex_macros))
    f.write("\n")

print("Don't forget to move numbers_auto.tex to the LaTeX repo ./Data/eval_wentao/")

# In[4]:

with open('kernel-results/per-perf-const-size.txt', 'r') as f:
    content = f.read()

with open('paper-assets/ss_instr_size.txt', 'w') as f:
    f.write(content)

print("Don't forget to move ss_instr_size.txt to plot repo ./cs_ss_func_size/")

# In[5]:

import glob

count_disjoint_sses = {}

for filename in glob.glob('kernel-results/*/ss-size2.txt'):
    skip=False
    for skip_macro in skip_macro_list:
        if filename == f'kernel-results/{skip_macro}/ss-size2.txt':
            skip=True
            break

    if skip:
        continue

    with open(filename) as f:
        # Number of spans with largest L value
        bb_lines = [line for line in f if 'BB' in line]
        count_disjoint_sses[filename] = len(bb_lines)

with open('paper-assets/disjoint_sses.txt', 'w') as f:
    for fname, count in count_disjoint_sses.items():
        f.write(f"{count}\n")

print("Don't forget to move disjoint_sses.txt to plot repo ./dataset/")
